#----------------------------------------------
# Configuraci\u00f3n general de la aplicaci\u00f3n
#----------------------------------------------

# Nombre de la aplicaci\u00f3n dentro del ecosistema Spring Boot.
spring.application.name=GestorBiblioteca

# Desactiva el uso de Google Cloud SQL en entorno local.
spring.cloud.gcp.sql.enabled=false

# URL de conexi\u00f3n a la base de datos MySQL en entorno local
spring.datasource.url=jdbc:mysql://localhost:3306/DBGestorBiblioteca?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
# Usuario de acceso a la base de datos.
spring.datasource.username=DBUserGestorBiblioteca
# Contrase\u00f1a del usuario de la base de datos.
spring.datasource.password=paso
# Driver JDBC utilizado para la conexi\u00f3n con MySQL.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Actualiza autom\u00e1ticamente la estructura de la base de datos seg\u00fan
# las entidades definidas en la aplicaci\u00f3n.
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en consola (para desarrollo)
spring.jpa.show-sql=true

# Dialecto de Hibernate para compatibilidad con MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Permite sobrescribir beans en caso de conflicto de configuraci\u00f3n
spring.main.allow-bean-definition-overriding=true