#------------------------------------
# Configuraci\u00f3n de Google Cloud SQL
#------------------------------------

#Habilita la integraci\u00f3n de Spring Boot con Google Cloud SQL.
spring.cloud.gcp.sql.enabled=true

# Identificador de la instancia de Cloud sql
spring.cloud.gcp.sql.instance-connection-name=tfggestorbibliotecaescolar:us-central1:gestorbiblioteca
# Nombre de la base de datos utilizada para la aplicaci\u00f3n
spring.cloud.gcp.sql.database-name=BDGestorBiblioteca


# Usuario con permisos sobre la base de datos.
spring.datasource.username=root
# Contrase\u00f1a del usuario de la base de datos.
spring.datasource.password=|jxdvF)Lx(qoUm~j

#Dialecto utilizado por Hibernate para generar consultar compatibles con MySQL.
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Actualiza autom\u00e1ticamente la estructura de la base de datos seg\u00fan
# las entidades definidas en la aplicaci\u00f3n.
spring.jpa.hibernate.ddl-auto=update
# Desactiva la visualizaci\u00f3n de consultas SQL en la consola
spring.jpa.show-sql=false

# Puerto de ejecuci\u00f3n de la aplicaci\u00f3n.
# En Google Cloud se utiliza la varible de entorno PORT.
server.port=${PORT:8080}

# Evita errores al serializar objetos vac\u00edos mediante Jackson.

spring.jackson.serialization.fail-on-empty-beans=false